[tool.poetry]
name = "octotail"
version = "1.0.2"
description = "Live tail GitHub Actions runs on git push"
authors = ["Rare»ô Cosma <rares@getbetter.ro>"]
license = "UNLICENSE"
readme = "README.md"
homepage = "https://github.com/rarescosma/octotail"
repository = "https://github.com/rarescosma/octotail"
documentation = "https://octotail.readthedocs.io/"
keywords = ["github-actions", "tail", "post-receive", "codecrafters", "git"]
classifiers = [
   "Development Status :: 3 - Alpha",
   "Intended Audience :: Developers",
   "Programming Language :: Python :: 3",
]

include = ["examples"]

[tool.poetry.dependencies]
python = "^3.12.0"
fake-useragent = "1.5.1"
mitmproxy = "11.0.0"
pygithub = "2.4.0"
pykka = "4.0.2"
pyppeteer = "2.0.0"
pyppeteer-stealth = "2.7.4"
pyxdg = "0.28"
typer-slim = "0.12.5"
websockets = "10.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
